"""
SiteForge — ZIP Exporter
Splits the generated HTML into index.html, style.css, script.js and zips them.
Also generates a GitHub Pages deploy script.
"""

import io
import re
import zipfile


def _extract_css(html: str) -> tuple[str, str]:
    """Pull <style>...</style> blocks out of HTML and return (html_no_style, css)."""
    css_blocks = re.findall(r"<style[^>]*>(.*?)</style>", html, re.DOTALL | re.IGNORECASE)
    css = "\n\n".join(css_blocks)
    clean_html = re.sub(r"<style[^>]*>.*?</style>", "", html, flags=re.DOTALL | re.IGNORECASE)
    return clean_html, css


def _extract_js(html: str) -> tuple[str, str]:
    """Pull inline <script>...</script> blocks (non-src) from HTML."""
    js_blocks = re.findall(
        r"<script(?![^>]*\bsrc\b)[^>]*>(.*?)</script>", html, re.DOTALL | re.IGNORECASE
    )
    js = "\n\n".join(js_blocks)
    # Remove only inline scripts (keep external src= ones)
    clean_html = re.sub(
        r"<script(?![^>]*\bsrc\b)[^>]*>.*?</script>",
        "",
        html,
        flags=re.DOTALL | re.IGNORECASE,
    )
    return clean_html, js


def _inject_external_refs(html: str) -> str:
    """
    Replace the inline style/script placeholders with links to
    the external style.css and script.js files.
    """
    # Add <link rel="stylesheet"> before </head>
    html = html.replace(
        "</head>",
        '  <link rel="stylesheet" href="style.css">\n</head>',
        1,
    )
    # Add <script src="script.js"> before </body>
    html = html.replace(
        "</body>",
        '  <script src="script.js"></script>\n</body>',
        1,
    )
    return html


def build_zip(html: str, business_name: str = "website") -> bytes:
    """
    Given the full rendered HTML, produce a ZIP archive containing:
      - index.html  (HTML with external refs)
      - style.css   (all styles)
      - script.js   (all JS)
      - deploy.sh   (GitHub Pages helper)
    Returns the ZIP as bytes.
    """
    html_no_style, css = _extract_css(html)
    html_no_script, js = _extract_js(html_no_style)
    final_html = _inject_external_refs(html_no_script)

    slug = re.sub(r"[^a-z0-9]+", "-", business_name.lower()).strip("-") or "website"

    deploy_sh = f"""#!/bin/bash
# Deploy {business_name} to GitHub Pages
# Usage: bash deploy.sh <github-username>

set -e
USERNAME=${{1:-your-github-username}}
REPO="{slug}-website"

echo "Creating GitHub repo and deploying..."
git init
git add .
git commit -m "Initial site generated by SiteForge"
gh repo create "$USERNAME/$REPO" --public --source=. --remote=origin --push
git checkout -b gh-pages
git push origin gh-pages

echo ""
echo "Done! Your site will be live at:"
echo "  https://$USERNAME.github.io/$REPO"
"""

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("index.html", final_html)
        zf.writestr("style.css", css)
        zf.writestr("script.js", js)
        zf.writestr("deploy.sh", deploy_sh)

    return buffer.getvalue()
